# Namespace

kind: Namespace
apiVersion: v1
metadata:
  name: system
  labels:
    name: system

---

# Secret

# ConfigMap

kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-env
  namespace: system
data:
  PORT: "8070"

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-props
  namespace: system
data:
  container1.properties: |
    key=value

---

# Deployment

kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-system
  namespace: system
spec:
  selector:
    matchLabels:
      pod: system
  template:
    metadata:
      labels:
        pod: system
    spec:
      containers:
        - name: container-app
          image: ghcr.io/aleogr/k8s-app
          envFrom:
            - configMapRef:
                name: configmap-env
          volumeMounts:
            - name: volume-container1-properties
              mountPath: "/config"
              readOnly: true
          args: ["$(PORT)"]
      initContainers:
        - name: initcontainer-one
          image: cgr.dev/chainguard/busybox
          command: ['sh', '-c', 'sleep 60 && echo The app is running!']
      volumes:
        - name: volume-container1-properties
          configMap:
            name: configmap-props
            items:
              - key: "container1.properties"
                path: "container1.properties"

---

# Horizontal Pod Autoscaler

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: hpa-system
  namespace: system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-system
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---

# ClusterIP Service

kind: Service
apiVersion: v1
metadata:
  name: service-system
  namespace: system
spec:
  selector:
    pod: system
  ports:
    - name: port-api
      protocol: TCP
      port: 8070

---

# Ingress

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-system
  namespace: system
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: service-system
                port:
                  name: port-api
