# Deployment
# ClusterIP Service
# Ingress

#configmap (env var)
#horizontal pod autoscaling


# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-system
spec:
  selector:
    matchLabels:
      pod: system
  template:
    metadata:
      labels:
        pod: system
    spec:
      containers:
        - name: container-app
          image: ghcr.io/aleogr/k8s-app
          ports:
            - containerPort: 8080

---

# ClusterIP Service

apiVersion: v1
kind: Service
metadata:
  name: service-system
spec:
  selector:
    pod: system
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

# Ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-
