# ConfigMap

# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-system
spec:
  selector:
    matchLabels:
      pod: system
  template:
    metadata:
      labels:
        pod: system
    spec:
      containers:
        - name: container-app
          image: ghcr.io/aleogr/k8s-app
          ports:
            - containerPort: 8080
#      imagePullSecrets:
#        - name: secret-ghcr

---

# Horizontal Pod Autoscaler

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-system
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---

# ClusterIP Service

apiVersion: v1
kind: Service
metadata:
  name: service-system
spec:
  selector:
    pod: system
  ports:
    - name: port-api
      protocol: TCP
      port: 8080
      targetPort: 8080

---

# Ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-system
spec:
  ingressClassName: nginx
  rules:
    - host: system.aleogr.dev
      http:
        paths:
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: service-system
                port:
                  name: port-api
