apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dockerapp
  labels:
    app: dockerapp
spec:
  selector:
    matchLabels:
      app: dockerapp
  template:
    metadata:
      labels:
        app: dockerapp
    spec:
      containers:
        - name: container-dockerapp
          image: ghcr.io/aleogr/docker
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: secret-ghcr
